# Meta
name: 체험예술공간 꽃밭
description: 아동, 청소년과 가족을 위한 미술·연극 통합형 공연과 전시 교육 프로그램을 운영합니다.
url: http://ccotbbat.com
baseurl: ''

timezone: 'Asia/Seoul'
permalink: pretty

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

kramdown:
  input: GFM
  syntax_highlighter: rouge
  entity_output: :as_input
  hard_wrap: true

# collections
collections:
  courses:
    output: true
    permalink: /course/:path/
  works:
    output: true
    permalink: /work/:path/


defaults:
  -
    scope:
      path: _courses
    values:
      layout: course
  -
    scope:
      path: _works
    values:
      layout: work
