# Meta
title: 체험예술공간 꽃밭
description: 아동, 청소년과 가족을 위한 미술·연극 통합형 공연과 전시 교육 프로그램을 운영합니다.
url: https://ccotbbat.com
baseurl: ''
repository: mozo-works/ccotbbat

en:
  name: CCOTBBAT
  description: CCOTBBAT, a visual theatre company, is a professional arts group which integrates fine arts and theatre for performance and organizes art-experienced workshops.
  url: https://ccotbbat.com/en

timezone: 'Asia/Seoul'
permalink: pretty

# SEO
facebook:
  app_id: 618140558345676
  publisher: https://www.facebook.com/visualtheaterccot
logo: /assets/global/ccotbbat.gif

google_site_verification: ImNi4YCIDwp7AbqRHZU4IIXENZ6f4H_sVp6DGEk80Qk
google_analytics: UA-81266340-2

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

sass:
  style: :compressed

kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# collections
collections:
  courses:
    output: true
    permalink: /course/:path/
  press:
    output: true
    permalink: /press/:path/
  works:
    output: true
    permalink: /work/:path/
  en_works:
    output: true
    permalink: /en/work/:path/

defaults:
  -
    scope:
      path: _courses
    values:
      layout: course
  -
    scope:
      path: _press
    values:
      layout: press
  -
    scope:
      path: _works
    values:
      layout: work
  -
    scope:
      path: _en_works
    values:
      layout: en/work
  - 
    scope:
      path: assets/img
    values:
      image: true
  -
    scope:
      path: assets/press
    values:
      image: true
  -
    scope:
      path: assets/works
    values:
      image: true
